# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='agents.agent', verbose_name='agent')),
                ('service', models.ForeignKey(blank=True, help_text="Périmètre de validation d'un chef de service, y compris les sous-services.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='services.service', verbose_name='service de responsabilité')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils utilisateurs',
                'permissions': [('manage_users', 'Peut gérer les utilisateurs')],
            },
        ),
    ]
