# Generated by Django 5.2.17 on 2026-10-02 15:36

import apps.overtime.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('priorite', models.PositiveIntegerField(default=100, help_text='La plus petite valeur est examinée en premier.', verbose_name='priorité')),
                ('heure_debut', models.TimeField(blank=True, help_text="Laisser vide, avec l'heure de fin, pour couvrir toute la journée.", null=True, verbose_name='heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='heure de fin')),
                ('applicable_weekend', models.BooleanField(default=False, verbose_name='applicable le week-end')),
                ('applicable_ferie', models.BooleanField(default=False, verbose_name='applicable un jour férié')),
                ('plafond_journalier', models.PositiveIntegerField(blank=True, null=True, verbose_name='plafond journalier (minutes)')),
                ('plafond_mensuel', models.PositiveIntegerField(blank=True, null=True, verbose_name='plafond mensuel (minutes)')),
                ('coefficient', models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='coefficient')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('date_debut_validite', models.DateField(blank=True, null=True, verbose_name='début de validité')),
                ('date_fin_validite', models.DateField(blank=True, null=True, verbose_name='fin de validité')),
            ],
            options={
                'verbose_name': 'règle de calcul',
                'verbose_name_plural': 'règles de calcul',
                'ordering': ['priorite', 'nom'],
                'permissions': [('manage_rules', 'Peut gérer les règles de calcul')],
            },
        ),
        migrations.CreateModel(
            name='OvertimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('coefficient', models.DecimalField(decimal_places=3, default=1, help_text='Valeur de référence. Le calcul applique le coefficient de la règle retenue.', max_digits=6, verbose_name='coefficient par défaut')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "type d'heure",
                'verbose_name_plural': "types d'heures",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('pause_debut', models.TimeField(blank=True, null=True, verbose_name='début de pause')),
                ('pause_fin', models.TimeField(blank=True, null=True, verbose_name='fin de pause')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'horaire',
                'verbose_name_plural': 'horaires',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ORDRE_SERVICE', 'Ordre de service'), ('NOTE', 'Note'), ('AUTORISATION', 'Autorisation'), ('JUSTIFICATIF', 'Justificatif'), ('AUTRE', 'Autre document')], default='JUSTIFICATIF', max_length=20, verbose_name='type de document')),
                ('fichier', models.FileField(upload_to=apps.overtime.models.attachment_upload_to, verbose_name='fichier')),
                ('nom_original', models.CharField(max_length=150, verbose_name='nom du fichier')),
                ('taille', models.PositiveIntegerField(verbose_name='taille (octets)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='type MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_deposees', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('type', models.CharField(choices=[('NATIONAL', 'National'), ('OFFICIEL', 'Officiel'), ('LOCAL', 'Local'), ('EXCEPTIONNEL', 'Exceptionnel')], default='NATIONAL', max_length=20, verbose_name='type')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'jour férié',
                'verbose_name_plural': 'jours fériés',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'actif'], name='overtime_ho_date_e16132_idx')],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travail', models.DateField(verbose_name='date de travail')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('duree_minutes', models.PositiveIntegerField(verbose_name='durée (minutes)')),
                ('coefficient_applique', models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='coefficient appliqué')),
                ('ventilation', models.JSONField(blank=True, default=list, help_text='Détail des segments et de la règle utilisée au moment du calcul.', verbose_name='ventilation')),
                ('motif', models.TextField(verbose_name='motif')),
                ('activite', models.TextField(verbose_name='activité réalisée')),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant estimé')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En validation'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumis le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvé le')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='agents.agent', verbose_name='agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_creees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': "déclaration d'heures supplémentaires",
                'verbose_name_plural': "déclarations d'heures supplémentaires",
                'ordering': ['-date_travail', '-heure_debut'],
                'permissions': [('view_overtime', 'Peut consulter les heures supplémentaires'), ('add_overtime', 'Peut créer une déclaration'), ('change_overtime', 'Peut modifier une déclaration'), ('delete_overtime', 'Peut supprimer une déclaration'), ('submit_overtime', 'Peut soumettre une déclaration'), ('approve_overtime', 'Peut approuver une déclaration'), ('reject_overtime', 'Peut rejeter une déclaration'), ('view_all_overtime', 'Peut consulter toutes les déclarations'), ('validate_all_overtime', 'Peut valider hors de son service')],
            },
        ),
    ]
