# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overtime', '0001_initial'),
        ('services', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='workflow.workflowstep', verbose_name='étape en cours'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='overtime.overtimerequest', verbose_name='déclaration'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='regle_appliquee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='overtime.overtimerule', verbose_name='règle appliquée'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='type_heure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles', to='overtime.overtimetype', verbose_name="type d'heure"),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='type_heure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='overtime.overtimetype', verbose_name="type d'heure"),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Laisser vide pour un horaire commun à toute l'administration.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='services.service', verbose_name='service'),
        ),
        migrations.AddIndex(
            model_name='overtimerule',
            index=models.Index(fields=['actif', 'priorite'], name='overtime_ov_actif_0571e9_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['agent', 'date_travail'], name='overtime_ov_agent_i_96cc01_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['statut'], name='overtime_ov_statut_fa58a0_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['date_travail'], name='overtime_ov_date_tr_2b17c2_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['type_heure'], name='overtime_ov_type_he_680f2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(condition=models.Q(('duree_minutes__gt', 0)), name='overtime_duree_positive'),
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['jour_semaine', 'actif'], name='overtime_wo_jour_se_044ec5_idx'),
        ),
    ]
