# Generated by Django 5.2.17 on 2026-10-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_grades_fonctions'),
        ('overtime', '0002_initial'),
        ('services', '0003_reaffecter_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='activite',
            field=models.TextField(blank=True, default='', verbose_name='activité réalisée'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='motif',
            field=models.CharField(max_length=120, verbose_name='motif'),
        ),
        migrations.CreateModel(
            name='ListeJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listes_heures', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'liste journalière',
                'verbose_name_plural': 'listes journalières',
                'ordering': ['-date', 'service__code'],
            },
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='liste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='overtime.listejournaliere', verbose_name='liste du jour'),
        ),
        migrations.CreateModel(
            name='SignatureListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite', models.CharField(choices=[('AGENT', 'Agent'), ('CADRE', 'Cadre')], max_length=10, verbose_name='qualité')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='signé le')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures_listes', to='agents.agent', verbose_name='signataire')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='overtime.listejournaliere', verbose_name='liste')),
            ],
            options={
                'verbose_name': 'signature de liste',
                'verbose_name_plural': 'signatures de liste',
                'ordering': ['qualite', 'signed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='listejournaliere',
            constraint=models.UniqueConstraint(fields=('date', 'service'), name='liste_jour_service'),
        ),
        migrations.AddConstraint(
            model_name='signatureliste',
            constraint=models.UniqueConstraint(fields=('liste', 'agent', 'qualite'), name='signature_liste_unique'),
        ),
    ]
