# Generated by Django 5.2.17 on 2026-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_liste_journaliere_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name='observation'),
        ),
    ]
