# Generated by Django 5.2.17 on 2026-10-04 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_saisie_validee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='mois')),
                ('agents', models.PositiveIntegerField(default=0, verbose_name='agents')),
                ('nombre', models.PositiveIntegerField(default=0, verbose_name='saisies')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='durée (minutes)')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant')),
                ('cloture_le', models.DateTimeField(auto_now_add=True, verbose_name='clôturé le')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paies_cloturees', to=settings.AUTH_USER_MODEL, verbose_name='clôturé par')),
            ],
            options={
                'verbose_name': 'paiement des heures supplémentaires',
                'verbose_name_plural': 'paiements des heures supplémentaires',
                'ordering': ['-annee', '-mois'],
                'permissions': [('close_payroll', 'Peut clôturer la paie des heures supplémentaires')],
                'constraints': [models.UniqueConstraint(fields=('annee', 'mois'), name='paiement_mois_unique')],
            },
        ),
    ]
