# Generated by Django 5.2.17 on 2026-10-05 21:42

import apps.overtime.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_paiement_mois'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('fichier', models.FileField(upload_to=apps.overtime.models.presence_upload_to, verbose_name='fichier')),
                ('nom_original', models.CharField(max_length=150, verbose_name='nom du fichier')),
                ('taille', models.PositiveIntegerField(verbose_name='taille (octets)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='type MIME')),
                ('depose_le', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('depose_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_presence', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
            ],
            options={
                'verbose_name': 'liste de présence',
                'verbose_name_plural': 'listes de présence',
                'ordering': ['-date'],
            },
        ),
    ]
