# Generated by Django 5.2.17 on 2026-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_liste_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='effectifs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='effectifs'),
        ),
    ]
