# Generated by Django 5.2.17 on 2026-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_administration', models.CharField(default='Administration publique', max_length=200, verbose_name="nom de l'administration")),
                ('sigle', models.CharField(default='RDC', max_length=50, verbose_name='sigle')),
                ('devise', models.CharField(default='CDF', help_text="Libellé monétaire affiché. Le calcul utilise le taux horaire de l'agent.", max_length=10, verbose_name='devise')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contact')),
                ('jours_weekend', models.CharField(default='5,6', help_text='Jours ISO séparés par des virgules : 0 = lundi … 6 = dimanche.', max_length=20, verbose_name='jours de week-end')),
                ('plafond_journalier_minutes', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour ne pas appliquer de plafond global.', null=True, verbose_name='plafond journalier (minutes)')),
                ('plafond_mensuel_minutes', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour ne pas appliquer de plafond global.', null=True, verbose_name='plafond mensuel (minutes)')),
                ('taille_max_fichier_mo', models.PositiveIntegerField(default=5, verbose_name="taille maximale d'un fichier (Mo)")),
                ('elements_par_page', models.PositiveIntegerField(default=20, verbose_name='éléments par page')),
                ('autoriser_date_future', models.BooleanField(default=True, verbose_name='autoriser une date de travail future')),
                ('autoriser_agent_inactif', models.BooleanField(default=False, verbose_name='autoriser une déclaration pour un agent inactif')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'paramètres du site',
                'verbose_name_plural': 'paramètres du site',
            },
        ),
    ]
