# Generated by Django 5.2.17 on 2026-10-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='devise',
            field=models.CharField(default='CDF', help_text='Libellé monétaire affiché. Le calcul utilise le barème du grade et de la fonction.', max_length=10, verbose_name='devise'),
        ),
    ]
