# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('overtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'circuit de validation',
                'verbose_name_plural': 'circuits de validation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, verbose_name='nouveau statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='overtime.overtimerequest', verbose_name='déclaration')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_demandes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'événement de déclaration',
                'verbose_name_plural': 'événements de déclaration',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='ordre')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('limiter_au_service', models.BooleanField(default=True, help_text="Si coché, le valideur doit couvrir le service de l'agent, sauf permission explicite.", verbose_name="limiter au service de l'agent")),
                ('groupes', models.ManyToManyField(blank=True, related_name='etapes_workflow', to='auth.group', verbose_name='groupes autorisés')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='workflow.workflowdefinition', verbose_name='circuit')),
            ],
            options={
                'verbose_name': 'étape de validation',
                'verbose_name_plural': 'étapes de validation',
                'ordering': ['workflow', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROBATION', 'Approbation'), ('REJET', 'Rejet')], max_length=20, verbose_name='décision')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='overtime.overtimerequest', verbose_name='déclaration')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_validation', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('etape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='workflow.workflowstep', verbose_name='étape')),
            ],
            options={
                'verbose_name': 'décision de validation',
                'verbose_name_plural': 'décisions de validation',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'ordre'), name='workflow_step_ordre_unique'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='workflow_step_code_unique'),
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['demande', 'created_at'], name='workflow_va_demande_7d53dd_idx'),
        ),
    ]
