# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=32, unique=True, verbose_name='matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='grade')),
                ('fonction', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('date_engagement', models.DateField(blank=True, null=True, verbose_name="date d'engagement")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('RETRAITE', 'Retraité'), ('SORTI', 'Sorti')], default='ACTIF', max_length=20, verbose_name='statut')),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, help_text="Montant unitaire paramétré par l'administration. Aucun barème n'est codé en dur.", max_digits=12, verbose_name='taux horaire')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'ordering': ['nom', 'postnom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='agents_agen_nom_dcb716_idx'), models.Index(fields=['actif'], name='agents_agen_actif_022f8e_idx'), models.Index(fields=['service'], name='agents_agen_service_f2dab9_idx'), models.Index(fields=['statut'], name='agents_agen_statut_e97cdb_idx')],
            },
        ),
    ]
