# Generated by Django 5.2.17 on 2026-10-04 08:08

import apps.agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPEG, PNG ou WebP. Taille maximale : 2 Mo.', upload_to=apps.agents.models.agent_photo_path, verbose_name='photo'),
        ),
    ]
