# Generated by Django 5.2.17 on 2026-10-04 23:18

import django.db.models.deletion
from django.db import migrations, models


def copier_taux(apps, schema_editor):
    Agent = apps.get_model("agents", "Agent")
    Bareme = apps.get_model("agents", "Bareme")
    for agent in Agent.objects.exclude(grade_id=None).exclude(fonction_id=None).iterator():
        taux = agent.taux_horaire or 0
        bareme, created = Bareme.objects.get_or_create(
            grade_id=agent.grade_id,
            fonction_id=agent.fonction_id,
            defaults={"taux_horaire": taux, "actif": True},
        )
        if not created and not bareme.taux_horaire and taux:
            bareme.taux_horaire = taux
            bareme.save(update_fields=["taux_horaire"])


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_grades_fonctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_horaire', models.DecimalField(decimal_places=2, help_text='Montant horaire appliqué aux agents de ce grade et de cette fonction.', max_digits=12, verbose_name='taux horaire')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baremes', to='agents.fonction', verbose_name='fonction')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baremes', to='agents.grade', verbose_name='grade')),
            ],
            options={
                'verbose_name': 'barème',
                'verbose_name_plural': 'barèmes',
                'ordering': ['grade__ordre', 'fonction__ordre'],
                'constraints': [models.UniqueConstraint(fields=('grade', 'fonction'), name='bareme_grade_fonction')],
            },
        ),
        migrations.RunPython(copier_taux, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='agent',
            name='taux_horaire',
        ),
    ]
