# Generated by Django 5.2.17 on 2026-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_bareme_grade_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='abreviation',
            field=models.CharField(blank=True, help_text='Code court utilisé dans les listes du personnel, par exemple DIR, CD ou ATA1.', max_length=16, verbose_name='abréviation'),
        ),
    ]
