# Generated by Django 5.2.17 on 2026-10-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_grade_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, help_text='Place dans la liste déclarative. Vide : le nom sert de tri.', null=True, verbose_name='ordre dans la liste'),
        ),
    ]
