# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='identifiant objet')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='nouvelles valeurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='agent utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'ordering': ['-created_at'],
                'permissions': [('view_audit', "Peut consulter le journal d'audit")],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['model_name'], name='audit_audit_model_n_515731_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx')],
            },
        ),
    ]
