# Generated by Django 5.2.17 on 2026-10-02 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='année')),
                ('dernier', models.PositiveIntegerField(default=0, verbose_name='dernier numéro')),
            ],
            options={
                'verbose_name': 'séquence de rapport',
                'verbose_name_plural': 'séquences de rapport',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32, unique=True, verbose_name='numéro')),
                ('type_rapport', models.CharField(choices=[('INDIVIDUEL', 'Rapport individuel'), ('SERVICE', 'Rapport par service'), ('ADMINISTRATIF', 'Rapport administratif'), ('MENSUEL', 'Rapport mensuel'), ('EXCEL', 'Export Excel')], max_length=20, verbose_name='type')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], max_length=8, verbose_name='format')),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='début de période')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='fin de période')),
                ('filtres', models.JSONField(blank=True, default=dict, verbose_name='filtres')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
            ],
            options={
                'verbose_name': 'rapport généré',
                'verbose_name_plural': 'rapports générés',
                'ordering': ['-genere_le'],
                'permissions': [('view_reports', 'Peut consulter les rapports'), ('export_reports', 'Peut exporter les rapports')],
                'indexes': [models.Index(fields=['-genere_le'], name='reports_gen_genere__58b0b4_idx'), models.Index(fields=['type_rapport'], name='reports_gen_type_ra_b57a0e_idx')],
            },
        ),
    ]
