# Generated by Django 5.2.17 on 2026-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='type_rapport',
            field=models.CharField(choices=[('INDIVIDUEL', 'Rapport individuel'), ('SERVICE', 'Rapport par service'), ('ADMINISTRATIF', 'Rapport administratif'), ('MENSUEL', 'Rapport mensuel'), ('HISTORIQUE', 'Rapport historique'), ('EXCEL', 'Export Excel')], max_length=20, verbose_name='type'),
        ),
    ]
